function [stim_labels,conds_contrast] = abcd_set_contrasts_nback(short_flag,error_flag,extra_flag)
%function [stim_labels,conds_contrast] = abcd_set_contrasts_nback(short_flag,error_flag,extra_flag)
%
% Purpose: create struct array specifying contrasts to perform for nBack task
%
% Optional input:
%   short_flag: [0|1] use shortened names for conditions and contrasts
%    {default = 0}
%   error_flag: [0|1] encode error trials as separate events
%    {default = 0}
%   extra_flag: [0|1] create timing files for extra, orthogonal event encoding
%    (i.e. 'target','lure','nonlure')
%    {default = 0}
%
% Output:
%   stim_labels: list of the names of all conditions 
%   conds_contrast: struct array containing these fields:
%     groupA: cell array containing first set of condition names
%     groupB: cell array containing second set of condition names
%     name: contrast name
%
% Created:  12/14/16 by Don Hagler
% Prev Mod: 10/26/17 by Dani Cornejo
% Prev Mod: 12/11/17 by Don Hagler
% Last Mod: 06/20/24 by Don Hagler
%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if ~exist('short_flag','var') || isempty(short_flag), short_flag = 0; end;
if ~exist('error_flag','var') || isempty(error_flag), error_flag = 0; end;
if ~exist('extra_flag','var') || isempty(extra_flag), extra_flag = 0; end;

conds_contrast = [];
stim_labels = [];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if short_flag
  condtypes = {'2b','0b'};
  stimtypes = {'psf','ntf','ngf','plc'};
  extra_stimtypes = {'tg','lu','ln'};
else
  condtypes = {'2_back','0_back'};
  stimtypes = {'posface','neutface','negface','place'};
  extra_stimtypes = {'target','lure','nonlure'};
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if extra_flag
  stimtypes = cat(2,stimtypes,extra_stimtypes);
end;

condnames = {}; k = 1;
for i=1:length(condtypes)
  for j=1:length(stimtypes)
    if short_flag
      tmpname = sprintf('%s%s',condtypes{i},stimtypes{j});
    else
      tmpname = sprintf('%s_%s',condtypes{i},stimtypes{j});
    end
    condnames{k} = tmpname;
    k = k + 1;
    if error_flag
      if short_flag
        condnames{k} = [tmpname 'e'];
      else
        condnames{k} = [tmpname '_err'];
      end
      k = k + 1;
    end;
  end;
end;

if short_flag
  condnames = cat(2,condnames,'c');
else
  condnames = cat(2,condnames,'cue');
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if short_flag
  names_contrast = {...
    '0b'...
    '2b'...
    'plc'...
    'emo'...
    ...
    '2bv0b'...
    'fvplc'...
    'emovntf'...
    'ngfvntf'...
    'psfvntf'...
  };
  if extra_flag
    names_contrast = cat(2,names_contrast,{...
      'tg'...
      'lu'...
      'nl'...
      ...
      'tgvlu'...
      'tgvnl'...
      'luvnl'...
    });
  end
else
  names_contrast = {...
    '0_back'...
    '2_back'...
    'place'...
    'emotion'...
    ...
    '2_back_vs_0_back'...
    'face_vs_place'...
    'emotion_vs_neutface'...
    'negface_vs_neutface'...
    'posface_vs_neutface'...
  };
  if extra_flag
    names_contrast = cat(2,names_contrast,{...
      'target'...
      'lure'...
      'nonlure'...
      ...
      'target_vs_lure'...
      'target_vs_nonlure'...
      'lure_vs_nonlure'...
    });
  end
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if short_flag
  groupA = {...
    {'0bplc','0bngf','0bntf','0bpsf'};...
    {'2bplc','2bngf','2bntf','2bpsf'};...
    {'0bplc','2bplc'};...
    {'0bngf','2bngf','0bpsf','2bpsf'};...
    ...
    {'2bplc','2bngf','2bntf','2bpsf'};...
    {'0bngf','2bngf','0bntf','2bntf','0bpsf','2bpsf'};...
    {'0bngf','2bngf','0bpsf','2bpsf'};...
    {'0bngf','2bngf'};...
    {'0bpsf','2bpsf'};...
  };
  if extra_flag
    groupA = cat(1,groupA,{...
      {'0btg','2btg'};...
      {'0blu','2blu'};...
      {'0bnl','2bnl'};...
      ...
      {'0btg','2btg'};...
      {'0btg','2btg'};...
      {'0blu','2blu'};...
    });
  end
  groupB = {...
    [];...
    [];...
    [];...
    [];...
    ...
    {'0bplc','0bngf','0bntf','0bpsf'};...
    {'0bplc','2bplc'};...
    {'0bntf','2bntf'};...
    {'0bntf','2bntf'};...
    {'0bntf','2bntf'};...
  }; 
  if extra_flag
    groupB = cat(1,groupB,{...
      [];...
      [];...
      [];...
      ...
      {'0blu','2blu'};...
      {'0bnl','2bnl'};...
      {'0bnl','2bnl'};...
    });
  end;
else
  groupA = {...
    {'0_back_place','0_back_negface','0_back_neutface','0_back_posface'};...
    {'2_back_place','2_back_negface','2_back_neutface','2_back_posface'};...
    {'0_back_place','2_back_place'};...
    {'0_back_negface','2_back_negface','0_back_posface','2_back_posface'};...
    ...
    {'2_back_place','2_back_negface','2_back_neutface','2_back_posface'};...
    {'0_back_negface','2_back_negface','0_back_neutface','2_back_neutface','0_back_posface','2_back_posface'};...
    {'0_back_negface','2_back_negface','0_back_posface','2_back_posface'};...
    {'0_back_negface','2_back_negface'};...
    {'0_back_posface','2_back_posface'};...
  };
  if extra_flag
    groupA = cat(1,groupA,{...
      {'0_back_target','2_back_target'};...
      {'0_back_lure','2_back_lure'};...
      {'0_back_nonlure','2_back_nonlure'};...
      ...
      {'0_back_target','2_back_target'};...
      {'0_back_target','2_back_target'};...
      {'0_back_lure','2_back_lure'};...
    });
  end
  groupB = {...
    [];...
    [];...
    [];...
    [];...
    ...
    {'0_back_place','0_back_negface','0_back_neutface','0_back_posface'};...
    {'0_back_place','2_back_place'};...
    {'0_back_neutface','2_back_neutface'};...
    {'0_back_neutface','2_back_neutface'};...
    {'0_back_neutface','2_back_neutface'};...
  }; 

  if extra_flag
    groupB = cat(1,groupB,{...
      [];...
      [];...
      [];...
      ...
      {'0_back_lure','2_back_lure'};...
      {'0_back_nonlure','2_back_nonlure'};...
      {'0_back_nonlure','2_back_nonlure'};...  
    });
  end;
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

nconds = length(condnames);

stim_labels = {};
nevents = 0;
for i=1:nconds
  cond = condnames{i};
  nevents = nevents + 1;
  stim_labels{nevents} = sprintf('%s',cond);
end;


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

ncontrast = length(names_contrast);
for i=1:ncontrast
  conds_contrast(i).groupA = groupA{i};
  conds_contrast(i).groupB = groupB{i};
  conds_contrast(i).name = names_contrast{i}; 
end;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

