function [stim_labels,conds_contrast] = abcd_set_contrasts_sst(short_flag)
%function [stim_labels,conds_contrast] = abcd_set_contrasts_sst(short_flag)
%
% Purpose: create struct array specifying contrasts to perform for SST task
%
% Optional input:
%   short_flag: [0|1] use shortened names for conditions and contrasts
%    {default = 0}
%
% Output:
%   stim_labels: list of the names of all conditions 
%   conds_contrast: struct array containing these fields:
%     groupA: cell array containing first set of condition names
%     groupB: cell array containing second set of condition names
%     name: contrast name
%
% Based on abcd_set_contrast by Don Hagler 
%
% Created:  12/14/16 by Don Hagler
% Prev Mod: 10/03/17 by Dani Cornejo 
% Prev Mod: 11/18/17 by Don Hagler
% Last Mod: 06/20/24 by Don Hagler
%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if ~exist('short_flag','var') || isempty(short_flag), short_flag = 0; end;

conds_contrast = [];
stim_labels = [];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if short_flag
  condnames = {'cg','ig','clg','nrg',...
               'ilg','cs','is','ss'};
  names_contrast = {...
    'cgvfx'...
    'csvcg'...
    'isvcg'...
    'asvcg'...
    'csvis' ...
    'igvcg'...
    'igvis'...
  };
  groupA = {...
    {'cg'};...
    {'cs'};...
    {'is'};...
    {'cs','is'};...
    {'cs'};...
    {'ig'};...
    {'ig'};...
  };
  groupB = {...
    [];...
    {'cg'};...
    {'cg'};...
    {'cg'};...
    {'is'};... 
    {'cg'};...
    {'is'};...
  };
else
  condnames = {'correct_go','incorrect_go','correctlate_go','noresp_go',...
               'incorrectlate_go','correct_stop','incorrect_stop','ssd_stop'};
  names_contrast = {...
    'correct_go_vs_fixation'...
    'correct_stop_vs_correct_go'...
    'incorrect_stop_vs_correct_go'...
    'any_stop_vs_correct_go'...
    'correct_stop_vs_incorrect_stop' ...
    'incorrect_go_vs_correct_go'...
    'incorrect_go_vs_incorrect_stop'...
  };
  groupA = {...
    {'correct_go'};...
    {'correct_stop'};...
    {'incorrect_stop'};...
    {'correct_stop','incorrect_stop'};...
    {'correct_stop'};...
    {'incorrect_go'};...
    {'incorrect_go'};...
  };
  groupB = {...
    [];...
    {'correct_go'};...
    {'correct_go'};...
    {'correct_go'};...
    {'incorrect_stop'};... 
    {'correct_go'};...
    {'incorrect_stop'};...
  };
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

nconds = length(condnames);
stim_labels = {};
for i=1:nconds
  cond = condnames{i}; 
  stim_labels{i} = sprintf('%s',cond); 
end;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

ncontrast = length(names_contrast);
for i=1:ncontrast
  conds_contrast(i).groupA = groupA{i};
  conds_contrast(i).groupB = groupB{i};
  conds_contrast(i).name = names_contrast{i};
end;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

