function [stim_labels,conds_contrast] = abcd_set_contrasts_mid(short_flag,extra_flag)
%function [stim_labels,conds_contrast] = abcd_set_contrasts_mid(short_flag,extra_flag)
%
% Purpose: create struct array specifying contrasts to perform for MID task
%
% Optional input:
%   short_flag: [0|1] use shortened names for conditions and contrasts
%    {default = 0}
%   extra_flag: [0|1] include additional contrasts
%    {default = 0}
%
% Output:
%   stim_labels: list of the names of all conditions 
%   conds_contrast: struct array containing these fields:
%     groupA: cell array containing first set of condition names
%     groupB: cell array containing second set of condition names
%     name: contrast name
%
% Created:  12/14/16 by Don Hagler
% Prev Mod: 10/12/17 by Dani Cornejo 
% Prev Mod: 12/11/17 by Don Hagler
% Prev Mod: 03/28/24 by Don Hagler
% Last Mod: 06/20/24 by Don Hagler
% 

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if ~exist('short_flag','var') || isempty(short_flag), short_flag = 0; end;
if ~exist('extra_flag','var') || isempty(extra_flag), extra_flag = 0; end;

conds_contrast = [];
stim_labels = [];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if short_flag
  condnames = {'lr','sr','ll','sl','n'};
  stimnames = {'a','pf','nf'};
else
  condnames = {'large_reward','small_reward','large_loss','small_loss','neutral'};
  stimnames = {'antic','pos_feedback','neg_feedback'};
end

if ~extra_flag
  if short_flag
    names_contrast = {...
      'arvn'...
      'alvn'...
      'rpvnf'...
      'lpvnf'...
      'alrvn'...
      'asrvn'...
      'alvsr'...
      'allvn'...
      'aslvn'...
      'alvsl'...
    };
    groupA = {...
      {'lra','sra'};...
      {'lla','sla'};...
      {'lrpf','srpf'};...
      {'llpf','slpf'};...
      {'lra'};...
      {'sra'};...
      {'lra'};...
      {'lla'};...
      {'sla'};...
      {'lla'};...
    }; 
    groupB = {...
      {'na'};...
      {'na'};...
      {'lrnf','srnf'};...
      {'llnf','slnf'};...
      {'na'};...
      {'na'};...
      {'sra'};...
      {'na'};...
      {'na'};...
      {'sla'};...
    }; 
  else
    names_contrast = {...
      'antic_reward_vs_neutral'...
      'antic_loss_vs_neutral'...
      'reward_pos_vs_neg_feedback'...
      'loss_pos_vs_neg_feedback'...
      'antic_large_reward_vs_neutral'...
      'antic_small_reward_vs_neutral'...
      'antic_large_vs_small_reward'...
      'antic_large_loss_vs_neutral'...
      'antic_small_loss_vs_neutral'...
      'antic_large_vs_small_loss'...
    };
    groupA = {...
      {'large_reward_antic','small_reward_antic'};...
      {'large_loss_antic','small_loss_antic'};...
      {'large_reward_pos_feedback','small_reward_pos_feedback'};...
      {'large_loss_pos_feedback','small_loss_pos_feedback'};...
      {'large_reward_antic'};...
      {'small_reward_antic'};...
      {'large_reward_antic'};...
      {'large_loss_antic'};...
      {'small_loss_antic'};...
      {'large_loss_antic'};...
    }; 
    groupB = {...
      {'neutral_antic'};...
      {'neutral_antic'};...
      {'large_reward_neg_feedback','small_reward_neg_feedback'};...
      {'large_loss_neg_feedback','small_loss_neg_feedback'};...
      {'neutral_antic'};...
      {'neutral_antic'};...
      {'small_reward_antic'};...
      {'neutral_antic'};...
      {'neutral_antic'};...
      {'small_loss_antic'};...
    }; 
    names_contrast = {...
      'antic_reward_vs_neutral'...
      'antic_loss_vs_neutral'...
      'reward_pos_vs_neg_feedback'...
      'loss_pos_vs_neg_feedback'...
      'antic_large_reward_vs_neutral'...
      'antic_small_reward_vs_neutral'...
      'antic_large_vs_small_reward'...
      'antic_large_loss_vs_neutral'...
      'antic_small_loss_vs_neutral'...
      'antic_large_vs_small_loss'...
    };
    groupA = {...
      {'large_reward_antic','small_reward_antic'};...
      {'large_loss_antic','small_loss_antic'};...
      {'large_reward_pos_feedback','small_reward_pos_feedback'};...
      {'large_loss_pos_feedback','small_loss_pos_feedback'};...
      {'large_reward_antic'};...
      {'small_reward_antic'};...
      {'large_reward_antic'};...
      {'large_loss_antic'};...
      {'small_loss_antic'};...
      {'large_loss_antic'};...
    }; 
    groupB = {...
      {'neutral_antic'};...
      {'neutral_antic'};...
      {'large_reward_neg_feedback','small_reward_neg_feedback'};...
      {'large_loss_neg_feedback','small_loss_neg_feedback'};...
      {'neutral_antic'};...
      {'neutral_antic'};...
      {'small_reward_antic'};...
      {'neutral_antic'};...
      {'neutral_antic'};...
      {'small_loss_antic'};...
    }; 
  end
else
  if short_flag
    names_contrast = {...
      'a'...
      'pf'...
      'nf'...
      'arvn'...
      'alvn'...
      'alrvn'...
      'asrvn'...
      'allvn'...
      'aslvn'...
      'arvl'...
      'ar'...
      'al'...
      'alvsr'...
      'alvsl'...
      'alrvll'...
      'asrvsl'...
      'rpvnf'...
      'lpvnf'...
      'lrpvnf'...
      'srpvnf'...
      'llpvnf'...
      'slpvnf'...
      'npvnf'... 
    };
    groupA = {...
      {'sra','lra','sla','lla','na'};...
      {'srpf','lrpf','slpf','llpf','npf'};...
      {'srnf','lrnf','slnf','llnf','nnf'};...
      {'lra','sra'};...
      {'lla','sla'};...
      {'lra'};...
      {'sra'};...      
      {'lla'};...
      {'sla'};...
      {'lra','sra'};...
      {'lra','sra'};...
      {'lla','sla'};...
      {'lra'};...
      {'lla'};...
      {'lra'};...
      {'sra'};...
      {'lrpf','srpf'};...
      {'llpf','slpf'};...
      {'lrpf'};...
      {'srpf'};...
      {'llpf'};...
      {'slpf'};...
      {'npf'};...
    };
    groupB = {...
      [];...
      [];...
      [];...
      {'na'};...
      {'na'};...
      {'na'};...
      {'na'};...
      {'na'};...
      {'na'};...
      {'lla','sla'};...
      [];...
      [];...
      {'sra'};...
      {'sla'};...
      {'lla'};...
      {'sla'};...
      {'lrnf','srnf'};...
      {'llnf','slnf'};...
      {'lrnf'};...
      {'srnf'};...
      {'llnf'};...
      {'slnf'};...
      {'nnf'};...
    }; 
  else
    names_contrast = {...
      'antic'...
      'pos_feedback'...
      'neg_feedback'...
      'antic_reward_vs_neutral'...
      'antic_loss_vs_neutral'...
      'antic_large_reward_vs_neutral'...
      'antic_small_reward_vs_neutral'...
      'antic_large_loss_vs_neutral'...
      'antic_small_loss_vs_neutral'...
      'antic_reward_vs_loss'...
      'antic_reward'...
      'antic_loss'...
      'antic_large_vs_small_reward'...
      'antic_large_vs_small_loss'...
      'antic_large_reward_vs_large_loss'...
      'antic_small_reward_vs_small_loss'...
      'reward_pos_vs_neg_feedback'...
      'loss_pos_vs_neg_feedback'...
      'large_reward_pos_vs_neg_feedback'...
      'small_reward_pos_vs_neg_feedback'...
      'large_loss_pos_vs_neg_feedback'...
      'small_loss_pos_vs_neg_feedback'...
      'neutral_pos_vs_neg_feedback'... 
    };
    groupA = {...
      {'small_reward_antic','large_reward_antic','small_loss_antic','large_loss_antic','neutral_antic'};...
      {'small_reward_pos_feedback','large_reward_pos_feedback','small_loss_pos_feedback','large_loss_pos_feedback','neutral_pos_feedback'};...
      {'small_reward_neg_feedback','large_reward_neg_feedback','small_loss_neg_feedback','large_loss_neg_feedback','neutral_neg_feedback'};...
      {'large_reward_antic','small_reward_antic'};...
      {'large_loss_antic','small_loss_antic'};...
      {'large_reward_antic'};...
      {'small_reward_antic'};...
      {'large_loss_antic'};...
      {'small_loss_antic'};...
      {'large_reward_antic','small_reward_antic'};...
      {'large_reward_antic','small_reward_antic'};...
      {'large_loss_antic','small_loss_antic'};...
      {'large_reward_antic'};...
      {'large_loss_antic'};...
      {'large_reward_antic'};...
      {'small_reward_antic'};...
      {'large_reward_pos_feedback','small_reward_pos_feedback'};...
      {'large_loss_pos_feedback','small_loss_pos_feedback'};...
      {'large_reward_pos_feedback'};...
      {'small_reward_pos_feedback'};...
      {'large_loss_pos_feedback'};...
      {'small_loss_pos_feedback'};...
      {'neutral_pos_feedback'};...
    };
    groupB = {...
      [];...
      [];...
      [];...
      {'neutral_antic'};...
      {'neutral_antic'};...
      {'neutral_antic'};...
      {'neutral_antic'};...
      {'neutral_antic'};...
      {'neutral_antic'};...
      {'large_loss_antic','small_loss_antic'};...
      [];...
      [];...
      {'small_reward_antic'};...
      {'small_loss_antic'};...
      {'large_loss_antic'};...
      {'small_loss_antic'};...
      {'large_reward_neg_feedback','small_reward_neg_feedback'};...
      {'large_loss_neg_feedback','small_loss_neg_feedback'};...
      {'large_reward_neg_feedback'};...
      {'small_reward_neg_feedback'};...
      {'large_loss_neg_feedback'};...
      {'small_loss_neg_feedback'};...
      {'neutral_neg_feedback'};...
    }; 
  end
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

nconds = length(condnames);
nstims = length(stimnames);

stim_labels = {};
nevents = 0;
for i=1:nconds
  cond = condnames{i};
  for j=1:nstims
    stim = stimnames{j};
    nevents = nevents + 1;
    if short_flag
      stim_labels{nevents} = sprintf('%s%s',cond,stim);
    else
      stim_labels{nevents} = sprintf('%s_%s',cond,stim);
    end
  end;
end;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

ncontrast = length(names_contrast);
for i=1:ncontrast
  conds_contrast(i).groupA = groupA{i};
  conds_contrast(i).groupB = groupB{i};
  conds_contrast(i).name = names_contrast{i};
end;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

